CREATE TABLE IF NOT EXISTS trained_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_data JSONB NOT NULL,
    metadata JSONB NOT NULL,
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índice para busca rápida do modelo ativo
CREATE INDEX idx_trained_models_is_active ON trained_models(is_active);

-- Política de segurança
ALTER TABLE trained_models ENABLE ROW LEVEL SECURITY;

-- Permitir leitura pública
CREATE POLICY "Trained models are viewable by everyone"
    ON trained_models FOR SELECT
    USING (true);

-- Permitir inserção apenas por usuários autenticados
CREATE POLICY "Trained models can be inserted by authenticated users"
    ON trained_models FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');