// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://bsebqfxhjupuenxeatiq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZWJxZnhoanVwdWVueGVhdGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0NzQ1MjEsImV4cCI6MjA0NjA1MDUyMX0.hpVd1SyEH4d3RGEnIc1leFaKuutoYq-TsR6xZxDrLLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);